name: 📊Test
on: [push, pull_request]

jobs:
  static-checks:
    name: Generate random binary file and upload to artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate random binary file
        run: |
          dd if=/dev/urandom of=100M.dat bs=1048576 count=100

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: download
          path: |
            100M.dat
            README.md
